<a href="https://colab.research.google.com/github/Tanzir11/Computer_Vision_preprocessing/blob/main/tree/main/NumpyNumpy_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Extract a diagonal or construct a diagonal array
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

While using reshape function always keep in mind that the shape you're providing is compatible with the number of elements present in the numpy array.since i had 16 elements the shapes that i could use are (1,16), (2,8), (4,4),(8,2),(16,1) i can also go like (8,2,1), (8,2,1,1) and etc

In [ ]:
np.diag(x)

array([ 0,  5, 10, 15])

The -1 in (1,-1) signifies that the dataset can be 1 and the rest of the data which in this case was 16 and it wont just be about (-1) but instead any negative number on it's place and it's going to perform the same, just remember out of (x,y) only one of them would be negative not all. so either x can be nagetive or y never both. In the same manner i can also create a 3 dimensional data all that i have to keep in mind is that only 1 element will be negation and the product of the first 2 should be a factor of the total number of element present.

In [ ]:
 np.arange(16).reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
 np.arange(16).reshape(8,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
x = np.arange(16).reshape(-12345, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
y = np.arange(16).reshape(-122323,4,2)
y

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [ ]:
z = np.arange(16).reshape(-122323,4,3) # As we can see this will throw the error because 12 is not the factor of 16 but mearly has few values in their respective factors common which holds no weight
z

ValueError: cannot reshape array of size 16 into shape (4,3)

In [ ]:
# as the name suggest what i am getting is the diagonal elements of x
np.diag(x)

array([ 0,  5, 10, 15])

Also remember you can write the logic to get the diagonal elements form the matrices by doing i==j and it will fetch the result

In [ ]:
np.diag(x, k=2)

array([2, 7])

in our x metric k=0 is our main diagonal in a square metric which is a default parameter in this functions, but if we put k=1
* [[ 0,  1,  2,  3],
*  [ 4,  5,  6,  7],
*  [ 8,  9, 10, 11],
*  [12, 13, 14, 15]]

from above metric it will drop line (0,1,2,3) and (0,4,8,12) to create a minor metric and return us the diagonal of that metric**

In [ ]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [ ]:
np.diag(x, k=2)

array([2, 7])

In [ ]:
xx = np.arange(16).reshape(-1,8)
xx

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In the above example as we can it's not a square metric so in this case what it will do for a value of k=2 is that it will leave the first two values i.e
* [0,1]
* [8,9]

find the next square matrics i.e
* [2,3]
* [10,11]

and return us the diagonal of that matrix

In [ ]:
 np.diag(xx,k=2)

array([ 2, 11])

In [ ]:
np.diag(xx, k=1)

array([ 1, 10])

So far we have been able to fetch only one side of the main diagonal within a square metrix but what if we want to fetch the other side of the main diagonal within a square metric in that case we will give negative values of k to do so

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [ ]:
np.diag(x,k=-2)

array([ 8, 13])

In [ ]:
np.diag(x,k=-3)

array([12])

In [ ]:
np.diag(x,k=-4)

array([], dtype=int32)

What if we try to recall diagonal of a diagonal value what will happen. Let's see

In [ ]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

So yeah this part of the numpy can be considered weird the reason being the fact that it recreates a 4x4 matrics and try to fit the diagonal values in that

### Create a two-dimensional array with the flattened input as a diagonal

In [ ]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

So we have a list inside a list basically multidimensional and than it flattens it i.e it makes it [1,2,3,4] so it wont have any nested list and than puts that into a diagonal

**np.diagflat() again has a k parameter which exactly works the same as it did before**

In [ ]:
np.diagflat([[1,2],[3,4]], k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [ ]:
np.diagflat([[1,2],[3,4]], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
np.diagflat([[1,2],[3,4]], k=3)

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.diagflat([[1,2],[3,4]], k=-3)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0]])

### np.tri() is a function that's going to create a numpy array with ones and dimensions as specified

In [ ]:
np.tri(5, 5, -1, dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

Here k=0 so what it does is that it says leave the diagonal that has 0th index element and get the diagonals above it.

In [ ]:
np.tri(5,5,0,dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

Here k=1 so what it does is that it says leave the diagonal that has 1st index element and get the diagonals above it.

In [ ]:
np.tri(5,5,1,dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.tri(5,5,2,dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.tri(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

tril means lower triangle

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],0) # here k=0

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

It tried to keep the data into the lower triangle and whatever we had above it ignored

In [ ]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],1) # here k=1

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

Upper triangle thing

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

when k=0 we are saying leave the diagonal that has elements from column=0 in it and when k becomes 1 we are saiying that leave the diagonal that has elements from column=1 in it

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

As per python index convention i.e
a = [1,2,3,4]
a[-1] = 4
similarly
when we use -1 the last element is considered so here when we used -1 it referred to the last column which means elements from the last colums cannot appear over here which is happening

# Random number generator

## np.random.rand(a,b)
### axb metrix with random numbers ranging from 0 to 1, Note no tuple is necessassory

In [ ]:
print(f"Random number generation (from uniform destribution)")
print(np.random.rand(2,3))

Random number generation (from uniform destribution)
[[0.39734503 0.11412677 0.85010412]
 [0.27106511 0.77959529 0.10798851]]


In [ ]:
print(f"Random number generation (from uniform destribution)")
print(np.random.rand(2,3,4))

Random number generation (from uniform destribution)
[[[0.17881964 0.45257504 0.00505217 0.14490193]
  [0.14532007 0.43681006 0.66776857 0.96666104]
  [0.85050947 0.16032699 0.25435643 0.60805526]]

 [[0.14469532 0.17346848 0.84063552 0.19687263]
  [0.59704023 0.86702395 0.28252118 0.40029525]
  [0.57791883 0.98788883 0.73875345 0.13902201]]]


 As far as rand function is concerned it's going to give me output based on uniform distribution i.e a distribution that lies between 0 to 1

## np.random.randn(x,y)
### this will give us values betweem 0,1 but with equal interval

In [ ]:
print(f"Number of normal distribution with zero mean and standard deviation 1 i.e standard normal")
print(np.random.randn(4,5))

Number of normal distribution with zero mean and standard deviation 1 i.e standard normal
[[ 0.55459633  0.81103479  0.45082475 -0.0969363  -0.14922295]
 [-1.17033706  1.23851412  1.53125091  0.45668845  1.06578249]
 [ 1.19470756  2.64955316  0.13100997  0.72767877 -0.62976067]
 [ 0.67988043 -0.72077127 -0.57642732 -1.00035234  1.78084422]]


**If we want to generate any data between any some number we can use np.arange function and than reshape the value we got**

randn stands for standard normal distribution which basically has ***µ=0*** where ***µ*** is ***mean*** or we can say ***average*** and ***(standard deviation)=1*** for a whole dataset

## np.random.randint(x,y,z) where x,y is the range and z is the steps if i do not give steps it will give just 1 element in between

In [ ]:
print("Random integer vector:", np.random.randint(1,10))
print("\nRandom integer matrix")
np.random.randint(1,10)

Random integer vector: 4

Random integer matrix


9

In [ ]:
print(np.random.randint(1,80,(3,5))) # randint (low, high, number of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw", np.random.randint(1,5,10))

[[34 44 21 16 17]
 [62 22 53 13 35]
 [33 65 27 20 46]]

20 samples drawn from a dice throw [4 1 2 4 2 1 4 2 4 4]


# Reshaping

In [ ]:
from numpy.random import randint as ri
 # instead of calling randint again and again and again i will just call ri instead

In [ ]:
a = ri(1,100,30) # we are asking for 3 elements
a

array([93, 55, 59, 35, 81, 76, 55, 74, 17, 22, 73, 35, 46, 20, 10, 15, 13,
       41, 59, 34, 88, 34, 34, 85, 34, 97, 99, 63, 72, 88])

In [ ]:
b = a.reshape(2,3,5) # we have reshaped it
b

array([[[93, 55, 59, 35, 81],
        [76, 55, 74, 17, 22],
        [73, 35, 46, 20, 10]],

       [[15, 13, 41, 59, 34],
        [88, 34, 34, 85, 34],
        [97, 99, 63, 72, 88]]])

In [ ]:
c = a.reshape(6,-1) # reshaping it again
c

array([[93, 55, 59, 35, 81],
       [76, 55, 74, 17, 22],
       [73, 35, 46, 20, 10],
       [15, 13, 41, 59, 34],
       [88, 34, 34, 85, 34],
       [97, 99, 63, 72, 88]])

In [ ]:
print("\na looks line\n", a)
print("\nb looks line\n", b)
print("\nc looks line\n", c)


a looks line
 [93 55 59 35 81 76 55 74 17 22 73 35 46 20 10 15 13 41 59 34 88 34 34 85
 34 97 99 63 72 88]

b looks line
 [[[93 55 59 35 81]
  [76 55 74 17 22]
  [73 35 46 20 10]]

 [[15 13 41 59 34]
  [88 34 34 85 34]
  [97 99 63 72 88]]]

c looks line
 [[93 55 59 35 81]
 [76 55 74 17 22]
 [73 35 46 20 10]
 [15 13 41 59 34]
 [88 34 34 85 34]
 [97 99 63 72 88]]


In [ ]:
print("\nShape of a is:", a.shape)
print("\nShape of b is:", b.shape)
print("\nShape of c is:", c.shape)


Shape of a is: (30,)

Shape of b is: (2, 3, 5)

Shape of c is: (6, 5)


### np.sort() works like .sort function in python

In [ ]:
A = np.random.randint(1,100,10)
print("\nVector of random integers\n", "-"*50,"\n",A)
print("\nHere is the sorted vector\n", '-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [80 49 94  4 96 51 90 33 81  5]

Here is the sorted vector
 -------------------------------------------------- 
 [ 4  5 33 49 51 80 81 90 94 96]


### Below we had to implement np.sort but within np.sort there exists an argument that takes 'mergesort', 'quicksort', 'heapsort', 'mergesort', and 'timsort'.

In [ ]:
M = ri(1,100,25).reshape(5,5)
M

array([[29, 64, 40, 50, 74],
       [15,  5,  8, 51, 34],
       [93, 42, 19, 14, 52],
       [75,  6, 54, 82, 61],
       [45, 39, 99,  1, 63]])

**axis=0 means column wise(Vertically) and axis=1 is Row wise(Horizontally)**

In [ ]:
print("\n Here is the sorted matrix along each row\n", "-"*50,"\n",np.sort(M, kind='mergesort'))


 Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[29 40 50 64 74]
 [ 5  8 15 34 51]
 [14 19 42 52 93]
 [ 6 54 61 75 82]
 [ 1 39 45 63 99]]


np.sort(M, kind='mergesort') sorts the matrix M along each row using the mergesort algorithm. The output will be a new matrix where the elements within each row are sorted in ascending order. The resulting matrix will be printed below the line of dashes.

In [ ]:
print("\n Here is the sorted matrix along each column\n", "-"*50,"\n",np.sort(M,axis=0,kind='mergesort'))


 Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[15  5  8  1 34]
 [29  6 19 14 52]
 [45 39 40 50 61]
 [75 42 54 51 63]
 [93 64 99 82 74]]


np.sort(M, axis=0, kind='mergesort') sorts the matrix M along each column using the mergesort algorithm. The output will be a new matrix where the elements within each column are sorted in ascending order. The resulting matrix will also be printed below the line of dashes.

### .max() gives the maximum element within a numpy matrix

In [ ]:
print("Max of a:", M.max())
print("Max of b:",b.max())

Max of a: 99
Max of b: 99


In [ ]:
M

array([[29, 64, 40, 50, 74],
       [15,  5,  8, 51, 34],
       [93, 42, 19, 14, 52],
       [75,  6, 54, 82, 61],
       [45, 39, 99,  1, 63]])

In [ ]:
# It's moving through the row(because we have axis=1) spotting the index with greates value in that row and returning that
print("Max of a location:", M.argmax(axis=1))
print("Max of b location:", b.argmax(axis=1))
print("Max of c location:", c.argmax(axis=1))

Max of a location: [4 3 0 3 2]
Max of b location: [[0 0 1 0 0]
 [2 2 2 1 2]]
Max of c location: [0 0 0 3 0 1]


In [ ]:
# It's moving through the column(because we have axis=0) spotting the index with greates value in that column and returning that
print("Max of a location:", M.argmax(axis=0))
print("Max of b location: ", b.argmax(axis=0))
print("Max of c location:", c.argmax(axis=0))

Max of a location: [2 0 4 3 0]
Max of b location:  [[0 0 0 1 0]
 [1 0 0 1 1]
 [1 1 1 1 1]]
Max of c location: [5 5 1 4 5]


In [ ]:
# If we are not specifying any axis value it is returning the maximum value overall in that matrix
print("Max of a location:", M.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

Max of a location: 22
Max of b location: 26
Max of c location: 26


# Indexing and Slicing

In [ ]:
arr = np.arange(0,11)
print("Array",arr)

Array [ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
print("Element at 7th  index is", arr[7])

Element at 7th  index is 7


In [ ]:
# Below argument says that go from 3-6(6 won't be considered) with the interval of 2
print("Element from 3rd to 5th index are:", arr[3:6:2])

Element from 3rd to 5th index are: [3 5]


In [ ]:
print("Elements from last backwards are:", arr[-1:7:-1])

Elements from last backwards are: [10  9  8]


In [ ]:
print("3 Elements from last backwards are:", arr[-1:-7:2])

3 Elements from last backwards are: []


In [ ]:
arr = np.arange(1,20,2)
print("Arr", arr)

Arr [ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
print("Element at 2nd, 4th and 9th index are:", arr[[2,4,9]])

Element at 2nd, 4th and 9th index are: [ 5  9 19]


# Indexing Operation

In [ ]:
mat = np.array(ri(10,100,45)).reshape(3,5,3)
print("Matrix of random 2-digit number\n--------------------\n",mat)

Matrix of random 2-digit number
--------------------
 [[[60 43 41]
  [57 35 81]
  [34 66 81]
  [77 52 99]
  [47 42 74]]

 [[70 74 99]
  [87 28 92]
  [85 28 27]
  [52 29 55]
  [27 49 34]]

 [[79 31 77]
  [56 37 31]
  [99 23 35]
  [86 45 32]
  [87 76 91]]]


In [ ]:
# Dimension 1
print("In our original matrix mat at 0th index we have \n",mat[0])

In our original matrix mat at 0th index we have 
 [[60 43 41]
 [57 35 81]
 [34 66 81]
 [77 52 99]
 [47 42 74]]


In [ ]:
# Dimension 2
print("In our original  matrix mat at 1st index we have \n",mat[1])

In our original  matrix mat at 1st index we have 
 [[70 74 99]
 [87 28 92]
 [85 28 27]
 [52 29 55]
 [27 49 34]]


In [ ]:
# Dimension 3
print("Similarly in our original matrix mat at 2nd index we have \n",mat[2])

Similarly in our original matrix mat at 2nd index we have 
 [[79 31 77]
 [56 37 31]
 [99 23 35]
 [86 45 32]
 [87 76 91]]


In our original matrix mat if we want to access [37,25,97] from 2nd dimension this is how we would do that.
* 1st we will access the 2nd dimention by performing **mat[1]** operation now [37,25,97] is at 1st index of 2nd dimension and we would access it by doing **mat[1][1]**

In [ ]:
mat[1][1]

array([87, 28, 92])

Now if i just want to access 97 i would write mat[1][1][1]

In [ ]:
mat[1][1][2]

92

# Slicing Operation

In [ ]:
# Our task is to access the 1st index elements from a 1-Dimentional array
c=[]
for i in range(5):
    a=mat[0][i][1]
    c.append(a)
print(c)

[43, 35, 66, 52, 42]


In [ ]:
# Another approach to so is by
mat[0][:,1] # mat[0][:,1] means in matrix mat's 1st-Dimension sub matric's, [:,1] all the row but column 1

array([43, 35, 66, 52, 42])

In [ ]:
mat

array([[[60, 43, 41],
        [57, 35, 81],
        [34, 66, 81],
        [77, 52, 99],
        [47, 42, 74]],

       [[70, 74, 99],
        [87, 28, 92],
        [85, 28, 27],
        [52, 29, 55],
        [27, 49, 34]],

       [[79, 31, 77],
        [56, 37, 31],
        [99, 23, 35],
        [86, 45, 32],
        [87, 76, 91]]])

### Now our task is to select the first two column from all the dimensions into one metrix

In [ ]:
# Approach 1
for i in range(3):
    print(mat[i][:2,:])

[[60 43 41]
 [57 35 81]]
[[70 74 99]
 [87 28 92]]
[[79 31 77]
 [56 37 31]]


In [ ]:
# Approach 2
a = mat[0][0:3][0:2]
b = mat[1][0:3][0:2]
c = mat[2][0:3][0:2]
e = np.concatenate((np.concatenate((a,b), axis=0),c), axis=0)
e

array([[60, 43, 41],
       [57, 35, 81],
       [70, 74, 99],
       [87, 28, 92],
       [79, 31, 77],
       [56, 37, 31]])

**Alternative and the best from the bunch approach to perform the same task would be**

In [ ]:
# Approach 3
mat[0:3,[0,1]]

array([[[60, 43, 41],
        [57, 35, 81]],

       [[70, 74, 99],
        [87, 28, 92]],

       [[79, 31, 77],
        [56, 37, 31]]])

# Subseting

In [ ]:
mat

array([[[60, 43, 41],
        [57, 35, 81],
        [34, 66, 81],
        [77, 52, 99],
        [47, 42, 74]],

       [[70, 74, 99],
        [87, 28, 92],
        [85, 28, 27],
        [52, 29, 55],
        [27, 49, 34]],

       [[79, 31, 77],
        [56, 37, 31],
        [99, 23, 35],
        [86, 45, 32],
        [87, 76, 91]]])

In [ ]:
# We can also change the value of certain data if we want like
mat[1][0][2]=50
mat # when i will see this the value would have been changed

array([[[60, 43, 41],
        [57, 35, 81],
        [34, 66, 81],
        [77, 52, 99],
        [47, 42, 74]],

       [[70, 74, 50],
        [87, 28, 92],
        [85, 28, 27],
        [52, 29, 55],
        [27, 49, 34]],

       [[79, 31, 77],
        [56, 37, 31],
        [99, 23, 35],
        [86, 45, 32],
        [87, 76, 91]]])

In [ ]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit number\n---------------\n", mat)
mat>50

Matrix of random 2-digit number
---------------
 [[65 44 74 80 76]
 [72 45 20 26 61]
 [41 74 98 70 42]]


array([[ True, False,  True,  True,  True],
       [ True, False, False, False,  True],
       [False,  True,  True,  True, False]])

In [ ]:
print("Element greater than 50\n", mat[mat>50])

Element greater than 50
 [65 74 80 76 72 61 74 98 70]


# Universal Function

In [ ]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\m1st Matrix of random signle-digit number\n----------------------", mat1)
print("\m2st Matrix of random signle-digit number\n----------------------", mat2)

\m1st Matrix of random signle-digit number
---------------------- [[8 9 1]
 [5 1 5]
 [2 3 4]]
\m2st Matrix of random signle-digit number
---------------------- [[9 6 1]
 [3 4 3]
 [1 4 6]]


### To perform matrix multiplication always be aware of the dimention mxn,nxb should be the form of dimention

In [ ]:
mat1*mat2 # this is not an actual matrix multiplication this is index wise matrix multiplication

array([[72, 54,  1],
       [15,  4, 15],
       [ 2, 12, 24]])

In [ ]:
mat1@mat2 # Here we are performing the proper matrix multiplication

array([[100,  88,  41],
       [ 53,  54,  38],
       [ 31,  40,  35]])

## np.matmul(a,b) is a numpy function that performs matrix multiplication

In [ ]:
np.matmul(mat1,mat2)

array([[100,  88,  41],
       [ 53,  54,  38],
       [ 31,  40,  35]])

In [ ]:
print("\nDivision\n----------------------\n",mat1/0)


Division
----------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\tanze\AppData\Local\Temp\ipykernel_27420\2587647509.py:1: RuntimeWarning: divide by zero encountered in divide
  print("\nDivision\n----------------------\n",mat1/0)


In [ ]:
print("\nAddition\n----------------------\n",mat1+10) # 10 gets added in each element


Addition
----------------------
 [[18 19 11]
 [15 11 15]
 [12 13 14]]


In [ ]:
print("\nExponentiation, matrix cubed here\n----------------------\n",mat1**3)
print("\nExponentiation, finding root of matrix\n------------------\n",pow(mat1,2))


Exponentiation, matrix cubed here
----------------------
 [[512 729   1]
 [125   1 125]
 [  8  27  64]]

Exponentiation, finding root of matrix
------------------
 [[64 81  1]
 [25  1 25]
 [ 4  9 16]]


# Broadcasting

In [ ]:
start = np.zeros((4,4))
start = start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
# create a rank1 ndarray with 3 values
add_rows = np.array([1,0,2,5])
add_rows

array([1, 0, 2, 5])

In [ ]:
y = start + add_rows
y

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.]])

So in first column 1 gets added in each in 2nd 0 gets addend similary in 3rd 2 gets added and in fourth 5

In [ ]:
# If we want to perform column wise Broadcasting then we are supposed to perform transpose operation
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
add_cols

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
x = start+add_cols

In [ ]:
x

array([[100., 100., 100., 100.],
       [101., 101., 101., 101.],
       [102., 102., 102., 102.],
       [103., 103., 103., 103.]])

as we can see now we have column wise operations

# Array Math

In [ ]:
print("\nMat1\n",mat1)
print("\nMat2\n",mat2)


Mat1
 [[8 9 1]
 [5 1 5]
 [2 3 4]]

Mat2
 [[9 6 1]
 [3 4 3]
 [1 4 6]]


In [ ]:
print("\nSqrt Operation on each element of the metrix\n------------------------",np.sqrt(mat1))


Sqrt Operation on each element of the metrix
------------------------ [[2.82842712 3.         1.        ]
 [2.23606798 1.         2.23606798]
 [1.41421356 1.73205081 2.        ]]


In [ ]:
print("\nExponential Operation on each element of the metrix\n------------------------",'-'*50,"\n",np.exp(mat1))


Exponential Operation on each element of the metrix
------------------------ -------------------------------------------------- 
 [[2.98095799e+03 8.10308393e+03 2.71828183e+00]
 [1.48413159e+02 2.71828183e+00 1.48413159e+02]
 [7.38905610e+00 2.00855369e+01 5.45981500e+01]]


In [ ]:
print("\n10-base logarithm on each element of the metrix\n------------------------",np.log10(mat1))


10-base logarithm on each element of the metrix
------------------------ [[0.90308999 0.95424251 0.        ]
 [0.69897    0.         0.69897   ]
 [0.30103    0.47712125 0.60205999]]


In [ ]:
print("\nModulo reminder Operation on each element of the metrix\n------------------------",np.fmod(mat1, mat2))
mat1%mat2


Modulo reminder Operation on each element of the metrix
------------------------ [[8 3 0]
 [2 1 2]
 [0 3 4]]


array([[8, 3, 0],
       [2, 1, 2],
       [0, 3, 4]])